---


description: A simple Hello World GitHub Action
inputs:
  example-input:
    default: World
    description: An example input
    required: false
name: Hello World Action
#use sone inputs
runs:
  steps:
    - name: Say Nice Things
      run: |
        echo "Hello, ${{ inputs.example-input }}!"
      shell: bash
  using: composite