name: "Hello World Action"
description: "A simple Hello World GitHub Action"
inputs:
  example-input:
    description: "An example input"
    required: false
    default: "World"

runs:
  using: "composite"
  steps:
    - name: "Say Hello"
      shell: bash
      run: |
        echo "Hello, ${{ inputs.example-input }}!"